
path_captured: ""
path_cured: ""

classes: {
  0: 'Pessoa',
  1: 'Com_luva',
  2: 'Com_oculos',
  3: 'Com_capacete',
  4: 'Com_oculos_normal',
  5: 'Com_mascara',
  6: 'Sem_luva',
  7: 'Sem_oculos',
  8: 'Sem_capacete',
  9: 'Sem_mascara',
  10: 'Com_colete',
  11: 'Sem_colete',
  12: 'Com_chapeu'
}